### PR TITLE
WIP: Keylime protocol implementation

### PR DESCRIPTION
**Pull request by THS-on**
@iolivergithub this should generate now a valid quote claim (currently using tpm2-tools).
I think some response data is still missing but it works.

You don't actually send the quote signature for verification against the AK, right?

### CODE REVIEW

**Comment by iolivergithub** [comment]
Regaridng teh quote signature....I haven't implemented sending that yet, maybe I'll get around to that ( I should flag this as an issue) ironically the rules are setup for the.   I also don't sign the claim structure either...

**Comment by iolivergithub** [comment]
Can you summarise the changes to core, protocol_dispatcher and results py?  Merge is not possible at this time due to conflicts

**Review by iolivergithub — APPROVED** [review]

**Comment by iolivergithub** [comment]
> Can you summarise the changes to core, protocol_dispatcher and results py? Merge is not possible at this time due to conflicts

Just noticed these are the in build directory....thought  .gitignore had that commented to be ignored. ?

**Comment by THS-on** [comment]
> Just noticed these are the in build directory....thought .gitignore had that commented to be ignored. ?

Some build files where not excluded. The first commit removes them all and adds them to the .gitignore.

**Comment by THS-on** [comment]
I've now also added support for the UEFI eventlog.

**Comment by THS-on** [comment]
Reading PCRs will require to parse the `tpm2_pcrs` struct. I currently don't know a nice way to do that.

**Comment by iolivergithub** [comment]
> I've now also added support for the UEFI eventlog.

Just in time, I added the pretty printer for UEFI in u10 :-)

**Comment by iolivergithub** [comment]
> 

OK, well one of th nice things about using intents is that we don't have to support everything. We can come back to the pcrs later. If quote works then that's extreneky good already.

**Comment by tomoveu** [comment]
Wow, this is awesome @THS-on What a [TPMdev weekly call](https://developers.tpm.dev/events/tpmdev-online-call) leads to ! Amazing, @iolivergithub 🔥

**Comment by THS-on** [comment]
> OK, well one of th nice things about using intents is that we don't have to support everything. We can come back to the pcrs later. If quote works then that's extreneky good already.

Once I removed the last TODOs from the code and you confirmed that it works, I think we can merge this.

**Comment by iolivergithub** [comment]
Merged :-)

**Pull request merged**
